spring:
    datasource:
        url: jdbc:h2:mem:blockchaindb
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        database:
            platform: h2
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true 