spring:
    application:
        name: blockchain-service
        
server:
    port: 8087

google:
    cloud:
        web3:
            uri: ${CLOUD_URI:https://blockchain.googleapis.com/v1/projects/nexworkproject/locations/us-central1/endpoints/ethereum-sepolia/rpc?key=AIzaSyBsWJRhK6dRSbBXovp1_HKX42nhBWGs_Tw}
    private:
        key: ${CLOUD_PK:81e6dd1514757600f3bc84563e512db9250a655fc1d905f11248c8633d8dd824}
        
logging:
  level:
    root: INFO
    ar.edu.unlam.tpi.accounts: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
