
spring:
    aplication:
        name: blockchain-api
    profiles:
        active: local
    
server:
    port: 8081

google:
    cloud:
        web3:
            uri: https://blockchain.googleapis.com/v1/projects/nexworkproject/locations/us-central1/endpoints/ethereum-sepolia/rpc?key=AIzaSyBsWJRhK6dRSbBXovp1_HKX42nhBWGs_Tw

private:
    key: 81e6dd1514757600f3bc84563e512db9250a655fc1d905f11248c8633d8dd824